#!/usr/bin/env tsx
/**
 * Vietnamese Law MCP — Census Script
 *
 * Enumerates ALL Vietnamese national legislation (Laws, Codes, Ordinances)
 * from the National Assembly and Standing Committee.
 *
 * Sources:
 *   - Curated master list based on vbpl.vn (National Legal Document Database)
 *   - Cross-referenced with thuvienphapluat.vn URLs
 *
 * Vietnamese legislation hierarchy (top-level only — what we ingest):
 *   - Hiến pháp (Constitution)
 *   - Bộ luật (Codes) — e.g., Bộ luật Hình sự, Bộ luật Dân sự
 *   - Luật (Laws) — passed by National Assembly (Quốc hội)
 *   - Pháp lệnh (Ordinances) — issued by Standing Committee
 *
 * We do NOT ingest sub-law instruments (Nghị định/Decrees, Thông tư/Circulars,
 * Quyết định/Decisions) except for Decree 13/2023/NĐ-CP (Personal Data
 * Protection) due to its standalone significance.
 *
 * Writes data/census.json in golden standard format.
 *
 * Usage:
 *   npx tsx scripts/census.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DATA_DIR = path.resolve(__dirname, '../data');
const CENSUS_PATH = path.join(DATA_DIR, 'census.json');

interface CensusLaw {
  id: string;
  title: string;
  title_en: string;
  short_name: string;
  official_number: string;
  type: 'constitution' | 'code' | 'law' | 'ordinance' | 'decree';
  status: 'in_force' | 'amended' | 'repealed' | 'not_yet_in_force';
  issued_date: string;
  in_force_date: string;
  url: string;
  description: string;
  classification: 'ingestable' | 'inaccessible' | 'metadata_only';
}

interface CensusOutput {
  generated_at: string;
  source: string;
  description: string;
  stats: {
    total: number;
    by_type: Record<string, number>;
    by_status: Record<string, number>;
    class_ingestable: number;
    class_inaccessible: number;
    class_metadata_only: number;
  };
  ingestion?: {
    completed_at: string;
    total_laws: number;
    total_provisions: number;
    coverage_pct: string;
  };
  laws: CensusLaw[];
}

/**
 * Master census of Vietnamese national legislation.
 *
 * This is a curated, comprehensive list built from:
 *   - vbpl.vn National Legal Document Database (62K+ documents, filtered to Laws/Codes/Ordinances)
 *   - thuvienphapluat.vn cross-referencing
 *   - Official Gazette (vanban.chinhphu.vn)
 *   - National Assembly session records (15th Legislature, 2021-2026)
 *
 * Coverage: Constitution + all major Codes + Laws from 1st through 15th National Assembly +
 *           key Ordinances + Decree 13/2023 (PDP).
 *
 * Last verified: 2026-02-26
 */
const VIETNAMESE_LAWS: CensusLaw[] = [
  // ===== CONSTITUTION =====
  {
    id: 'constitution-2013',
    title: 'Hiến pháp nước Cộng hòa xã hội chủ nghĩa Việt Nam 2013',
    title_en: 'Constitution of the Socialist Republic of Vietnam 2013',
    short_name: 'Hiến pháp 2013',
    official_number: 'N/A',
    type: 'constitution',
    status: 'in_force',
    issued_date: '2013-11-28',
    in_force_date: '2014-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Hien-phap-nam-2013-215627.aspx',
    description: 'Supreme law of Vietnam. Guarantees right to privacy (Art. 21), freedom of speech (Art. 25), property rights (Art. 32).',
    classification: 'ingestable',
  },

  // ===== CODES (Bộ luật) =====
  {
    id: 'civil-code-2015',
    title: 'Bộ luật Dân sự 2015',
    title_en: 'Civil Code 2015',
    short_name: 'BLDS 2015',
    official_number: '91/2015/QH13',
    type: 'code',
    status: 'in_force',
    issued_date: '2015-11-24',
    in_force_date: '2017-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Quyen-dan-su/Bo-luat-dan-su-2015-296215.aspx',
    description: 'Comprehensive civil law code: property, contracts, torts, inheritance, intellectual property. 689 articles.',
    classification: 'ingestable',
  },
  {
    id: 'civil-procedure-code-2015',
    title: 'Bộ luật Tố tụng dân sự 2015',
    title_en: 'Civil Procedure Code 2015',
    short_name: 'BLTTDS 2015',
    official_number: '92/2015/QH13',
    type: 'code',
    status: 'in_force',
    issued_date: '2015-11-25',
    in_force_date: '2016-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thu-tuc-To-tung/Bo-luat-to-tung-dan-su-2015-296861.aspx',
    description: 'Civil procedure code governing courts, jurisdiction, evidence, appeals. 517 articles.',
    classification: 'ingestable',
  },
  {
    id: 'penal-code-2015',
    title: 'Bộ luật Hình sự 2015',
    title_en: 'Penal Code 2015',
    short_name: 'BLHS 2015',
    official_number: '100/2015/QH13',
    type: 'code',
    status: 'amended',
    issued_date: '2015-11-27',
    in_force_date: '2018-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Trach-nhiem-hinh-su/Bo-luat-hinh-su-2015-296661.aspx',
    description: 'Criminal code. Articles 285-294 cover cybercrimes. Amended by Law 12/2017/QH14.',
    classification: 'ingestable',
  },
  {
    id: 'criminal-procedure-code-2015',
    title: 'Bộ luật Tố tụng hình sự 2015',
    title_en: 'Criminal Procedure Code 2015',
    short_name: 'BLTTHS 2015',
    official_number: '101/2015/QH13',
    type: 'code',
    status: 'in_force',
    issued_date: '2015-11-27',
    in_force_date: '2018-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Trach-nhiem-hinh-su/Bo-luat-to-tung-hinh-su-2015-296884.aspx',
    description: 'Criminal procedure code: investigation, prosecution, trial, appeals, enforcement. 510 articles.',
    classification: 'ingestable',
  },
  {
    id: 'labour-code-2019',
    title: 'Bộ luật Lao động 2019',
    title_en: 'Labour Code 2019',
    short_name: 'BLLĐ 2019',
    official_number: '45/2019/QH14',
    type: 'code',
    status: 'in_force',
    issued_date: '2019-11-20',
    in_force_date: '2021-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Lao-dong-Tien-luong/Bo-Luat-lao-dong-2019-333670.aspx',
    description: 'Labour code: employment contracts, wages, working hours, occupational safety, trade unions, dispute resolution. 220 articles.',
    classification: 'ingestable',
  },
  {
    id: 'maritime-code-2015',
    title: 'Bộ luật Hàng hải Việt Nam 2015',
    title_en: 'Maritime Code 2015',
    short_name: 'BLHH 2015',
    official_number: '95/2015/QH13',
    type: 'code',
    status: 'in_force',
    issued_date: '2015-11-25',
    in_force_date: '2017-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Giao-thong-Van-tai/Bo-luat-hang-hai-Viet-Nam-2015-298250.aspx',
    description: 'Maritime law code: shipping, ports, maritime commerce, carriage of goods, marine insurance. 341 articles.',
    classification: 'ingestable',
  },

  // ===== LAWS — CYBERSECURITY, DATA PROTECTION, ICT =====
  {
    id: 'cybersecurity-law-2018',
    title: 'Luật An ninh mạng 2018',
    title_en: 'Cybersecurity Law 2018',
    short_name: 'Luật ANMT 2018',
    official_number: '24/2018/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2018-06-12',
    in_force_date: '2019-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Cong-nghe-thong-tin/Luat-An-ninh-mang-2018-351416.aspx',
    description: 'Comprehensive cybersecurity law: data localization, critical infrastructure protection, content regulation, incident response.',
    classification: 'ingestable',
  },
  {
    id: 'network-information-security-law-2015',
    title: 'Luật An toàn thông tin mạng 2015',
    title_en: 'Law on Network Information Security 2015',
    short_name: 'Luật ATTTM 2015',
    official_number: '86/2015/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2015-11-19',
    in_force_date: '2016-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Cong-nghe-thong-tin/Luat-an-toan-thong-tin-mang-2015-298365.aspx',
    description: 'Information security framework: classification, protection measures, CII protection, incident response, encryption policy.',
    classification: 'ingestable',
  },
  {
    id: 'information-technology-law-2006',
    title: 'Luật Công nghệ thông tin 2006',
    title_en: 'Law on Information Technology 2006',
    short_name: 'Luật CNTT 2006',
    official_number: '67/2006/QH11',
    type: 'law',
    status: 'in_force',
    issued_date: '2006-06-29',
    in_force_date: '2007-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Cong-nghe-thong-tin/Luat-Cong-nghe-thong-tin-2006-67-2006-QH11-12987.aspx',
    description: 'Foundational IT law: IT applications, digital content, e-government, IT industry development, information security.',
    classification: 'ingestable',
  },
  {
    id: 'telecommunications-law-2023',
    title: 'Luật Viễn thông 2023',
    title_en: 'Law on Telecommunications 2023',
    short_name: 'Luật VT 2023',
    official_number: '24/2023/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2023-11-24',
    in_force_date: '2024-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Cong-nghe-thong-tin/Luat-Vien-thong-2023-24-2023-QH15-583722.aspx',
    description: 'New telecommunications law replacing 2009 version. Cloud computing, OTT services, data center regulation, 5G spectrum.',
    classification: 'ingestable',
  },
  {
    id: 'telecommunications-law-2009',
    title: 'Luật Viễn thông 2009',
    title_en: 'Law on Telecommunications 2009',
    short_name: 'Luật VT 2009',
    official_number: '41/2009/QH12',
    type: 'law',
    status: 'amended',
    issued_date: '2009-11-23',
    in_force_date: '2010-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Cong-nghe-thong-tin/Luat-vien-thong-2009-41-2009-QH12-98328.aspx',
    description: 'Telecommunications regulation: licensing, interconnection, spectrum, subscriber data. Largely replaced by 2023 law.',
    classification: 'ingestable',
  },
  {
    id: 'e-transactions-law-2023',
    title: 'Luật Giao dịch điện tử 2023',
    title_en: 'Law on E-Transactions 2023',
    short_name: 'Luật GDĐT 2023',
    official_number: '20/2023/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2023-06-22',
    in_force_date: '2024-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Cong-nghe-thong-tin/Luat-Giao-dich-dien-tu-2023-20-2023-QH15-567171.aspx',
    description: 'E-transactions: electronic signatures, digital certificates, electronic contracts, trust services, blockchain recognition.',
    classification: 'ingestable',
  },
  {
    id: 'data-law-2024',
    title: 'Luật Dữ liệu 2024',
    title_en: 'Law on Data 2024',
    short_name: 'Luật DL 2024',
    official_number: '60/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-11-30',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Cong-nghe-thong-tin/Luat-Du-lieu-2024-60-2024-QH15-637052.aspx',
    description: 'New data governance law: data sovereignty, national data strategy, open data, data exchange platform, data-driven government.',
    classification: 'ingestable',
  },
  {
    id: 'personal-data-protection-law-2025',
    title: 'Luật Bảo vệ dữ liệu cá nhân 2025',
    title_en: 'Law on Personal Data Protection 2025',
    short_name: 'Luật BVDLCN 2025',
    official_number: '91/2025/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2025-06-26',
    in_force_date: '2026-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Cong-nghe-thong-tin/Luat-Bao-ve-du-lieu-ca-nhan-2025-91-2025-QH15-675268.aspx',
    description: 'Vietnam\'s first standalone personal data protection law. Replaces/supplements Decree 13/2023. GDPR-influenced. Data subject rights, DPO requirements, cross-border transfers.',
    classification: 'ingestable',
  },

  // ===== LAWS — COMMERCE, ENTERPRISE, COMPETITION =====
  {
    id: 'enterprise-law-2020',
    title: 'Luật Doanh nghiệp 2020',
    title_en: 'Enterprise Law 2020',
    short_name: 'Luật DN 2020',
    official_number: '59/2020/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2020-06-17',
    in_force_date: '2021-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Doanh-nghiep/Luat-Doanh-nghiep-2020-so-59-2020-QH14-437468.aspx',
    description: 'Enterprise/company law: LLC, JSC, partnership, private enterprise; corporate governance, shareholder rights, dissolution.',
    classification: 'ingestable',
  },
  {
    id: 'investment-law-2020',
    title: 'Luật Đầu tư 2020',
    title_en: 'Investment Law 2020',
    short_name: 'Luật ĐT 2020',
    official_number: '61/2020/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2020-06-17',
    in_force_date: '2021-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Doanh-nghiep/Luat-Dau-tu-2020-so-61-2020-QH14-437486.aspx',
    description: 'Investment law: foreign investment, investment registration, incentives, special economic zones, PPPs.',
    classification: 'ingestable',
  },
  {
    id: 'commercial-law-2005',
    title: 'Luật Thương mại 2005',
    title_en: 'Commercial Law 2005',
    short_name: 'Luật TM 2005',
    official_number: '36/2005/QH11',
    type: 'law',
    status: 'in_force',
    issued_date: '2005-06-14',
    in_force_date: '2006-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thuong-mai/Luat-Thuong-mai-2005-36-2005-QH11-4044.aspx',
    description: 'Commercial law: sale of goods, service contracts, commercial representation, trade promotion, trade remedies.',
    classification: 'ingestable',
  },
  {
    id: 'competition-law-2018',
    title: 'Luật Cạnh tranh 2018',
    title_en: 'Law on Competition 2018',
    short_name: 'Luật CT 2018',
    official_number: '23/2018/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2018-06-12',
    in_force_date: '2019-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thuong-mai/Luat-canh-tranh-2018-23-2018-QH14-353991.aspx',
    description: 'Competition/antitrust: anti-competitive agreements, abuse of dominance, merger control, unfair practices.',
    classification: 'ingestable',
  },
  {
    id: 'consumer-rights-protection-law-2023',
    title: 'Luật Bảo vệ quyền lợi người tiêu dùng 2023',
    title_en: 'Law on Protection of Consumer Rights 2023',
    short_name: 'Luật BVQLNTD 2023',
    official_number: '19/2023/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2023-06-20',
    in_force_date: '2024-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thuong-mai/Luat-Bao-ve-quyen-loi-nguoi-tieu-dung-2023-19-2023-QH15-567169.aspx',
    description: 'Consumer protection: e-commerce consumer rights, platform liability, data protection, dispute resolution.',
    classification: 'ingestable',
  },
  {
    id: 'securities-law-2019',
    title: 'Luật Chứng khoán 2019',
    title_en: 'Law on Securities 2019',
    short_name: 'Luật CK 2019',
    official_number: '54/2019/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2019-11-26',
    in_force_date: '2021-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Chung-khoan/Luat-Chung-khoan-2019-54-2019-QH14-405758.aspx',
    description: 'Securities regulation: stock exchange, public offering, disclosure requirements, insider trading, market manipulation.',
    classification: 'ingestable',
  },
  {
    id: 'credit-institutions-law-2024',
    title: 'Luật Các tổ chức tín dụng 2024',
    title_en: 'Law on Credit Institutions 2024',
    short_name: 'Luật TCTD 2024',
    official_number: '32/2024/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2024-01-18',
    in_force_date: '2024-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Tien-te-Ngan-hang/Luat-Cac-to-chuc-tin-dung-2024-32-2024-QH15-599564.aspx',
    description: 'Banking and credit institutions: licensing, governance, deposits, lending, special control, resolution.',
    classification: 'ingestable',
  },
  {
    id: 'insurance-business-law-2022',
    title: 'Luật Kinh doanh bảo hiểm 2022',
    title_en: 'Law on Insurance Business 2022',
    short_name: 'Luật KDBH 2022',
    official_number: '08/2022/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2022-06-16',
    in_force_date: '2023-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bao-hiem/Luat-Kinh-doanh-bao-hiem-2022-08-2022-QH15-519924.aspx',
    description: 'Insurance regulation: life/non-life, reinsurance, insurance intermediaries, solvency requirements.',
    classification: 'ingestable',
  },
  {
    id: 'bankruptcy-law-2014',
    title: 'Luật Phá sản 2014',
    title_en: 'Law on Bankruptcy 2014',
    short_name: 'Luật PS 2014',
    official_number: '51/2014/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2014-06-19',
    in_force_date: '2015-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Doanh-nghiep/Luat-pha-san-2014-51-2014-QH13-238640.aspx',
    description: 'Bankruptcy/insolvency: debt recovery, reorganization, liquidation, creditor rights.',
    classification: 'ingestable',
  },

  // ===== LAWS — TAX, FINANCE =====
  {
    id: 'tax-administration-law-2019',
    title: 'Luật Quản lý thuế 2019',
    title_en: 'Law on Tax Administration 2019',
    short_name: 'Luật QLT 2019',
    official_number: '38/2019/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2019-06-13',
    in_force_date: '2020-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thue-Phi-Le-Phi/Luat-Quan-ly-thue-2019-38-2019-QH14-415825.aspx',
    description: 'Tax administration: registration, filing, assessment, collection, transfer pricing, e-invoicing.',
    classification: 'ingestable',
  },
  {
    id: 'vat-law-2024',
    title: 'Luật Thuế giá trị gia tăng 2024',
    title_en: 'Law on Value-Added Tax 2024',
    short_name: 'Luật GTGT 2024',
    official_number: '48/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-11-26',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thue-Phi-Le-Phi/Luat-Thue-gia-tri-gia-tang-2024-48-2024-QH15-637020.aspx',
    description: 'New VAT law: rates, exemptions, e-commerce VAT, digital service taxation, cross-border services.',
    classification: 'ingestable',
  },
  {
    id: 'corporate-income-tax-law-2008',
    title: 'Luật Thuế thu nhập doanh nghiệp 2008',
    title_en: 'Law on Corporate Income Tax 2008',
    short_name: 'Luật TNDN 2008',
    official_number: '14/2008/QH12',
    type: 'law',
    status: 'amended',
    issued_date: '2008-06-03',
    in_force_date: '2009-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thue-Phi-Le-Phi/Luat-thue-thu-nhap-doanh-nghiep-2008-14-2008-QH12-63762.aspx',
    description: 'Corporate income tax: rates, incentives, deductions, transfer pricing.',
    classification: 'ingestable',
  },
  {
    id: 'personal-income-tax-law-2007',
    title: 'Luật Thuế thu nhập cá nhân 2007',
    title_en: 'Law on Personal Income Tax 2007',
    short_name: 'Luật TNCN 2007',
    official_number: '04/2007/QH12',
    type: 'law',
    status: 'amended',
    issued_date: '2007-11-21',
    in_force_date: '2009-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thue-Phi-Le-Phi/Luat-Thue-thu-nhap-ca-nhan-2007-04-2007-QH12-19744.aspx',
    description: 'Personal income tax: rates, brackets, withholding, non-resident taxation.',
    classification: 'ingestable',
  },
  {
    id: 'accounting-law-2015',
    title: 'Luật Kế toán 2015',
    title_en: 'Law on Accounting 2015',
    short_name: 'Luật KT 2015',
    official_number: '88/2015/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2015-11-20',
    in_force_date: '2017-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Ke-toan-Kiem-toan/Luat-ke-toan-2015-298141.aspx',
    description: 'Accounting standards: bookkeeping, financial statements, audit requirements, accounting profession.',
    classification: 'ingestable',
  },
  {
    id: 'independent-audit-law-2011',
    title: 'Luật Kiểm toán độc lập 2011',
    title_en: 'Law on Independent Audit 2011',
    short_name: 'Luật KTĐL 2011',
    official_number: '67/2011/QH12',
    type: 'law',
    status: 'in_force',
    issued_date: '2011-03-29',
    in_force_date: '2012-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Ke-toan-Kiem-toan/Luat-kiem-toan-doc-lap-2011-67-2011-QH12-120873.aspx',
    description: 'Independent audit regulation: audit firms, auditor qualifications, audit standards, liability.',
    classification: 'ingestable',
  },
  {
    id: 'state-budget-law-2015',
    title: 'Luật Ngân sách nhà nước 2015',
    title_en: 'Law on State Budget 2015',
    short_name: 'Luật NSNN 2015',
    official_number: '83/2015/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2015-06-25',
    in_force_date: '2017-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Tai-chinh-nha-nuoc/Luat-ngan-sach-nha-nuoc-2015-282443.aspx',
    description: 'State budget: budget cycle, revenue/expenditure, fiscal decentralization, public debt management.',
    classification: 'ingestable',
  },
  {
    id: 'anti-money-laundering-law-2022',
    title: 'Luật Phòng, chống rửa tiền 2022',
    title_en: 'Law on Anti-Money Laundering 2022',
    short_name: 'Luật PCRT 2022',
    official_number: '14/2022/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2022-11-15',
    in_force_date: '2023-03-01',
    url: 'https://thuvienphapluat.vn/van-ban/Tien-te-Ngan-hang/Luat-Phong-chong-rua-tien-2022-14-2022-QH15-535866.aspx',
    description: 'AML law: CDD, suspicious transaction reporting, beneficial ownership, PEP screening, international cooperation.',
    classification: 'ingestable',
  },

  // ===== LAWS — INTELLECTUAL PROPERTY =====
  {
    id: 'intellectual-property-law-2005',
    title: 'Luật Sở hữu trí tuệ 2005',
    title_en: 'Law on Intellectual Property 2005',
    short_name: 'Luật SHTT 2005',
    official_number: '50/2005/QH11',
    type: 'law',
    status: 'amended',
    issued_date: '2005-11-29',
    in_force_date: '2006-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/So-huu-tri-tue/Luat-So-huu-tri-tue-2005-50-2005-QH11-5765.aspx',
    description: 'IP law: copyright, patents, trademarks, industrial designs, trade secrets, geographical indications. Amended 2009, 2019, 2022.',
    classification: 'ingestable',
  },

  // ===== LAWS — LAND, REAL ESTATE, CONSTRUCTION =====
  {
    id: 'land-law-2024',
    title: 'Luật Đất đai 2024',
    title_en: 'Land Law 2024',
    short_name: 'Luật ĐĐ 2024',
    official_number: '31/2024/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2024-01-18',
    in_force_date: '2024-08-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bat-dong-san/Luat-Dat-dai-2024-31-2024-QH15-599565.aspx',
    description: 'Land law: land use rights, allocation, lease, compensation, conversion, land database, digital land registry.',
    classification: 'ingestable',
  },
  {
    id: 'housing-law-2023',
    title: 'Luật Nhà ở 2023',
    title_en: 'Housing Law 2023',
    short_name: 'Luật NỞ 2023',
    official_number: '27/2023/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2023-11-27',
    in_force_date: '2025-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bat-dong-san/Luat-Nha-o-2023-27-2023-QH15-583720.aspx',
    description: 'Housing: ownership, development, social housing, real estate transactions, foreign ownership.',
    classification: 'ingestable',
  },
  {
    id: 'construction-law-2014',
    title: 'Luật Xây dựng 2014',
    title_en: 'Law on Construction 2014',
    short_name: 'Luật XD 2014',
    official_number: '50/2014/QH13',
    type: 'law',
    status: 'amended',
    issued_date: '2014-06-18',
    in_force_date: '2015-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Xay-dung-Do-thi/Luat-xay-dung-2014-238644.aspx',
    description: 'Construction: permits, quality management, construction safety, contractor licensing.',
    classification: 'ingestable',
  },
  {
    id: 'real-estate-business-law-2023',
    title: 'Luật Kinh doanh bất động sản 2023',
    title_en: 'Law on Real Estate Business 2023',
    short_name: 'Luật KDBĐS 2023',
    official_number: '29/2023/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2023-11-28',
    in_force_date: '2025-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bat-dong-san/Luat-Kinh-doanh-bat-dong-san-2023-29-2023-QH15-583721.aspx',
    description: 'Real estate business: brokerage, development, property management, foreign investment in real estate.',
    classification: 'ingestable',
  },

  // ===== LAWS — ENVIRONMENT, NATURAL RESOURCES =====
  {
    id: 'environmental-protection-law-2020',
    title: 'Luật Bảo vệ môi trường 2020',
    title_en: 'Law on Environmental Protection 2020',
    short_name: 'Luật BVMT 2020',
    official_number: '72/2020/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2020-11-17',
    in_force_date: '2022-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Tai-nguyen-Moi-truong/Luat-Bao-ve-moi-truong-2020-72-2020-QH14-453129.aspx',
    description: 'Environmental protection: EIA, pollution control, waste management, emissions trading, climate change adaptation.',
    classification: 'ingestable',
  },

  // ===== LAWS — JUDICIARY, ADMINISTRATIVE =====
  {
    id: 'administrative-procedure-law-2015',
    title: 'Luật Tố tụng hành chính 2015',
    title_en: 'Law on Administrative Procedures 2015',
    short_name: 'Luật TTHC 2015',
    official_number: '93/2015/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2015-11-25',
    in_force_date: '2016-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thu-tuc-To-tung/Luat-To-tung-hanh-chinh-2015-296862.aspx',
    description: 'Administrative procedure: administrative lawsuits against government, judicial review, state liability.',
    classification: 'ingestable',
  },
  {
    id: 'administrative-violations-law-2012',
    title: 'Luật Xử lý vi phạm hành chính 2012',
    title_en: 'Law on Handling of Administrative Violations 2012',
    short_name: 'Luật XLVPHC 2012',
    official_number: '15/2012/QH13',
    type: 'law',
    status: 'amended',
    issued_date: '2012-06-20',
    in_force_date: '2013-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Vi-pham-hanh-chinh/Luat-xu-ly-vi-pham-hanh-chinh-2012-15-2012-QH13-142838.aspx',
    description: 'Administrative sanctions: fines, additional penalties, enforcement measures, complaint mechanisms.',
    classification: 'ingestable',
  },
  {
    id: 'anti-corruption-law-2018',
    title: 'Luật Phòng, chống tham nhũng 2018',
    title_en: 'Law on Anti-Corruption 2018',
    short_name: 'Luật PCTN 2018',
    official_number: '36/2018/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2018-11-20',
    in_force_date: '2019-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Luat-phong-chong-tham-nhung-2018-36-2018-QH14-399962.aspx',
    description: 'Anti-corruption: asset declaration, conflicts of interest, whistleblower protection, private sector obligations.',
    classification: 'ingestable',
  },
  {
    id: 'inspection-law-2022',
    title: 'Luật Thanh tra 2022',
    title_en: 'Law on Inspection 2022',
    short_name: 'Luật TT 2022',
    official_number: '11/2022/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2022-11-14',
    in_force_date: '2023-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Luat-Thanh-tra-2022-11-2022-QH15-535867.aspx',
    description: 'Government inspection: administrative inspection, specialized inspection, complaint handling, inspection procedures.',
    classification: 'ingestable',
  },
  {
    id: 'complaints-law-2011',
    title: 'Luật Khiếu nại 2011',
    title_en: 'Law on Complaints 2011',
    short_name: 'Luật KN 2011',
    official_number: '02/2011/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2011-11-11',
    in_force_date: '2012-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thu-tuc-To-tung/Luat-khieu-nai-2011-02-2011-QH13-131760.aspx',
    description: 'Complaints law: citizen complaints against administrative decisions, complaint resolution procedures.',
    classification: 'ingestable',
  },
  {
    id: 'denunciation-law-2018',
    title: 'Luật Tố cáo 2018',
    title_en: 'Law on Denunciation 2018',
    short_name: 'Luật TC 2018',
    official_number: '25/2018/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2018-06-12',
    in_force_date: '2019-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thu-tuc-To-tung/Luat-to-cao-2018-25-2018-QH14-356578.aspx',
    description: 'Whistleblowing/denunciation: reporting violations, whistleblower protection, investigation procedures.',
    classification: 'ingestable',
  },
  {
    id: 'state-compensation-law-2017',
    title: 'Luật Trách nhiệm bồi thường của Nhà nước 2017',
    title_en: 'Law on State Compensation Liability 2017',
    short_name: 'Luật TNBTNN 2017',
    official_number: '10/2017/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2017-06-20',
    in_force_date: '2018-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Trach-nhiem-hinh-su/Luat-trach-nhiem-boi-thuong-cua-Nha-nuoc-2017-322898.aspx',
    description: 'State compensation liability: government liability for wrongful acts, compensation procedures and amounts.',
    classification: 'ingestable',
  },

  // ===== LAWS — HEALTHCARE, SOCIAL =====
  {
    id: 'health-insurance-law-2008',
    title: 'Luật Bảo hiểm y tế 2008',
    title_en: 'Law on Health Insurance 2008',
    short_name: 'Luật BHYT 2008',
    official_number: '25/2008/QH12',
    type: 'law',
    status: 'amended',
    issued_date: '2008-11-14',
    in_force_date: '2009-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bao-hiem/Luat-bao-hiem-y-te-2008-25-2008-QH12-82128.aspx',
    description: 'Health insurance: mandatory coverage, benefits, provider networks, co-payments.',
    classification: 'ingestable',
  },
  {
    id: 'social-insurance-law-2024',
    title: 'Luật Bảo hiểm xã hội 2024',
    title_en: 'Law on Social Insurance 2024',
    short_name: 'Luật BHXH 2024',
    official_number: '41/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-06-29',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bao-hiem/Luat-Bao-hiem-xa-hoi-2024-41-2024-QH15-617638.aspx',
    description: 'Social insurance: pensions, unemployment, maternity, occupational injury, voluntary insurance.',
    classification: 'ingestable',
  },
  {
    id: 'pharmacy-law-2024',
    title: 'Luật Dược 2024',
    title_en: 'Law on Pharmacy 2024',
    short_name: 'Luật D 2024',
    official_number: '44/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-11-21',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/The-thao-Y-te/Luat-Duoc-2024-44-2024-QH15-636968.aspx',
    description: 'Pharmaceutical regulation: drug registration, manufacturing standards, distribution, pricing.',
    classification: 'ingestable',
  },

  // ===== LAWS — EDUCATION, PRESS, MEDIA =====
  {
    id: 'education-law-2019',
    title: 'Luật Giáo dục 2019',
    title_en: 'Law on Education 2019',
    short_name: 'Luật GD 2019',
    official_number: '43/2019/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2019-06-14',
    in_force_date: '2020-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Giao-duc/Luat-Giao-duc-2019-43-2019-QH14-395428.aspx',
    description: 'Education system: compulsory education, higher education, vocational training, teacher qualifications.',
    classification: 'ingestable',
  },
  {
    id: 'press-law-2016',
    title: 'Luật Báo chí 2016',
    title_en: 'Press Law 2016',
    short_name: 'Luật BC 2016',
    official_number: '103/2016/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2016-04-05',
    in_force_date: '2017-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Van-hoa-Xa-hoi/Luat-bao-chi-2016-103-2016-QH13-303840.aspx',
    description: 'Press regulation: press activities, journalist rights, content regulation, online media.',
    classification: 'ingestable',
  },
  {
    id: 'access-to-information-law-2016',
    title: 'Luật Tiếp cận thông tin 2016',
    title_en: 'Law on Access to Information 2016',
    short_name: 'Luật TCTT 2016',
    official_number: '104/2016/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2016-04-06',
    in_force_date: '2018-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Luat-tiep-can-thong-tin-2016-303848.aspx',
    description: 'Freedom of information: public information access, proactive disclosure, request procedures.',
    classification: 'ingestable',
  },
  {
    id: 'archives-law-2024',
    title: 'Luật Lưu trữ 2024',
    title_en: 'Law on Archives 2024',
    short_name: 'Luật LT 2024',
    official_number: '33/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-06-21',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Luat-Luu-tru-2024-33-2024-QH15-617639.aspx',
    description: 'Archives: digital archiving, electronic records management, national archive system.',
    classification: 'ingestable',
  },

  // ===== LAWS — TRANSPORT, INFRASTRUCTURE =====
  {
    id: 'road-traffic-law-2024',
    title: 'Luật Trật tự, an toàn giao thông đường bộ 2024',
    title_en: 'Law on Road Traffic Order and Safety 2024',
    short_name: 'Luật TTATGTĐB 2024',
    official_number: '36/2024/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2024-06-27',
    in_force_date: '2025-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Giao-thong-Van-tai/Luat-Trat-tu-an-toan-giao-thong-duong-bo-2024-36-2024-QH15-617641.aspx',
    description: 'Road traffic safety: vehicle registration, licensing, traffic rules, traffic cameras, enforcement.',
    classification: 'ingestable',
  },
  {
    id: 'civil-aviation-law-2006',
    title: 'Luật Hàng không dân dụng Việt Nam 2006',
    title_en: 'Law on Civil Aviation 2006',
    short_name: 'Luật HKDD 2006',
    official_number: '66/2006/QH11',
    type: 'law',
    status: 'amended',
    issued_date: '2006-06-29',
    in_force_date: '2007-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Giao-thong-Van-tai/Luat-hang-khong-dan-dung-Viet-Nam-2006-66-2006-QH11-12966.aspx',
    description: 'Civil aviation: air transport, airports, aircraft registration, air safety.',
    classification: 'ingestable',
  },
  {
    id: 'railway-law-2017',
    title: 'Luật Đường sắt 2017',
    title_en: 'Law on Railways 2017',
    short_name: 'Luật ĐS 2017',
    official_number: '06/2017/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2017-06-16',
    in_force_date: '2018-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Giao-thong-Van-tai/Luat-Duong-sat-2017-06-2017-QH14-318689.aspx',
    description: 'Railway regulation: rail infrastructure, train operations, safety, urban rail transit.',
    classification: 'ingestable',
  },

  // ===== LAWS — DEFENSE, SECURITY, PUBLIC ORDER =====
  {
    id: 'national-defense-law-2018',
    title: 'Luật Quốc phòng 2018',
    title_en: 'Law on National Defense 2018',
    short_name: 'Luật QP 2018',
    official_number: '22/2018/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2018-06-08',
    in_force_date: '2019-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Luat-Quoc-phong-2018-22-2018-QH14-350881.aspx',
    description: 'National defense: military organization, defense industry, civil defense, state of emergency.',
    classification: 'ingestable',
  },
  {
    id: 'peoples-public-security-law-2018',
    title: 'Luật Công an nhân dân 2018',
    title_en: 'Law on People\'s Public Security 2018',
    short_name: 'Luật CAND 2018',
    official_number: '37/2018/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2018-11-20',
    in_force_date: '2019-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Luat-Cong-an-nhan-dan-2018-37-2018-QH14-399972.aspx',
    description: 'Public security forces: organization, police powers, cyber police, intelligence.',
    classification: 'ingestable',
  },
  {
    id: 'fire-prevention-law-2024',
    title: 'Luật Phòng cháy, chữa cháy và cứu nạn, cứu hộ 2024',
    title_en: 'Law on Fire Prevention, Firefighting and Rescue 2024',
    short_name: 'Luật PCCC 2024',
    official_number: '55/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-11-29',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Tai-nguyen-Moi-truong/Luat-Phong-chay-chua-chay-2024-55-2024-QH15-637050.aspx',
    description: 'Fire prevention and firefighting: fire safety standards, building requirements, emergency response.',
    classification: 'ingestable',
  },

  // ===== LAWS — TRADE UNION, LABOR =====
  {
    id: 'trade-union-law-2024',
    title: 'Luật Công đoàn 2024',
    title_en: 'Law on Trade Unions 2024',
    short_name: 'Luật CĐ 2024',
    official_number: '50/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-11-27',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Lao-dong-Tien-luong/Luat-Cong-doan-2024-50-2024-QH15-637024.aspx',
    description: 'Trade union law: union organization, worker representation, collective bargaining, union finances.',
    classification: 'ingestable',
  },
  {
    id: 'employment-law-2013',
    title: 'Luật Việc làm 2013',
    title_en: 'Law on Employment 2013',
    short_name: 'Luật VL 2013',
    official_number: '38/2013/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2013-11-16',
    in_force_date: '2015-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Lao-dong-Tien-luong/Luat-viec-lam-2013-215670.aspx',
    description: 'Employment: job creation, employment services, unemployment insurance, labor market.',
    classification: 'ingestable',
  },
  {
    id: 'occupational-safety-law-2015',
    title: 'Luật An toàn, vệ sinh lao động 2015',
    title_en: 'Law on Occupational Safety and Hygiene 2015',
    short_name: 'Luật ATVSLĐ 2015',
    official_number: '84/2015/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2015-06-25',
    in_force_date: '2016-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Lao-dong-Tien-luong/Luat-an-toan-ve-sinh-lao-dong-2015-282456.aspx',
    description: 'Workplace safety: hazard prevention, accident investigation, occupational health, compensation.',
    classification: 'ingestable',
  },

  // ===== LAWS — BIDDING, PUBLIC PROCUREMENT =====
  {
    id: 'bidding-law-2023',
    title: 'Luật Đấu thầu 2023',
    title_en: 'Law on Bidding 2023',
    short_name: 'Luật ĐT 2023',
    official_number: '22/2023/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2023-06-23',
    in_force_date: '2024-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Dau-tu/Luat-Dau-thau-2023-22-2023-QH15-567175.aspx',
    description: 'Public procurement: bidding procedures, e-procurement, contractor selection, contract management.',
    classification: 'ingestable',
  },
  {
    id: 'public-investment-law-2019',
    title: 'Luật Đầu tư công 2019',
    title_en: 'Law on Public Investment 2019',
    short_name: 'Luật ĐTC 2019',
    official_number: '39/2019/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2019-06-13',
    in_force_date: '2020-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Dau-tu/Luat-Dau-tu-cong-2019-39-2019-QH14-415826.aspx',
    description: 'Public investment: project appraisal, ODA management, capital allocation, public-private partnerships.',
    classification: 'ingestable',
  },

  // ===== LAWS — INTERNATIONAL TRADE =====
  {
    id: 'foreign-trade-management-law-2017',
    title: 'Luật Quản lý ngoại thương 2017',
    title_en: 'Law on Management of Foreign Trade 2017',
    short_name: 'Luật QLNT 2017',
    official_number: '05/2017/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2017-06-12',
    in_force_date: '2018-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thuong-mai/Luat-Quan-ly-ngoai-thuong-2017-05-2017-QH14-318685.aspx',
    description: 'Foreign trade: import/export, trade defense measures, trade promotion, origin of goods.',
    classification: 'ingestable',
  },
  {
    id: 'customs-law-2014',
    title: 'Luật Hải quan 2014',
    title_en: 'Customs Law 2014',
    short_name: 'Luật HQ 2014',
    official_number: '54/2014/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2014-06-23',
    in_force_date: '2015-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Xuat-nhap-khau/Luat-Hai-quan-2014-54-2014-QH13-238643.aspx',
    description: 'Customs regulation: customs procedures, tariffs, duty assessment, authorized economic operators.',
    classification: 'ingestable',
  },

  // ===== LAWS — NOTARIZATION, LEGAL PROFESSION =====
  {
    id: 'notarization-law-2024',
    title: 'Luật Công chứng 2024',
    title_en: 'Law on Notarization 2024',
    short_name: 'Luật CC 2024',
    official_number: '43/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-11-20',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Dich-vu-phap-ly/Luat-Cong-chung-2024-43-2024-QH15-636958.aspx',
    description: 'Notarization: digital notarization, notary office requirements, electronic documents.',
    classification: 'ingestable',
  },
  {
    id: 'lawyers-law-2006',
    title: 'Luật Luật sư 2006',
    title_en: 'Law on Lawyers 2006',
    short_name: 'Luật LS 2006',
    official_number: '65/2006/QH11',
    type: 'law',
    status: 'amended',
    issued_date: '2006-06-29',
    in_force_date: '2007-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Dich-vu-phap-ly/Luat-Luat-su-2006-65-2006-QH11-12965.aspx',
    description: 'Legal profession: lawyer licensing, bar association, legal aid, foreign lawyer practice.',
    classification: 'ingestable',
  },
  {
    id: 'commercial-arbitration-law-2010',
    title: 'Luật Trọng tài thương mại 2010',
    title_en: 'Law on Commercial Arbitration 2010',
    short_name: 'Luật TTTM 2010',
    official_number: '54/2010/QH12',
    type: 'law',
    status: 'in_force',
    issued_date: '2010-06-17',
    in_force_date: '2011-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thu-tuc-To-tung/Luat-trong-tai-thuong-mai-2010-54-2010-QH12-108044.aspx',
    description: 'Commercial arbitration: domestic and international arbitration, enforcement of arbitral awards.',
    classification: 'ingestable',
  },
  {
    id: 'mediation-dialogue-law-2020',
    title: 'Luật Hòa giải, đối thoại tại Tòa án 2020',
    title_en: 'Law on Mediation and Dialogue at Court 2020',
    short_name: 'Luật HGĐT 2020',
    official_number: '58/2020/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2020-06-16',
    in_force_date: '2021-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thu-tuc-To-tung/Luat-Hoa-giai-doi-thoai-tai-Toa-an-2020-58-2020-QH14-437466.aspx',
    description: 'Court mediation: pre-trial mediation, civil/administrative dialogue, mediator qualifications.',
    classification: 'ingestable',
  },

  // ===== LAWS — ENERGY, MINING =====
  {
    id: 'electricity-law-2004',
    title: 'Luật Điện lực 2004',
    title_en: 'Law on Electricity 2004',
    short_name: 'Luật ĐL 2004',
    official_number: '28/2004/QH11',
    type: 'law',
    status: 'amended',
    issued_date: '2004-12-03',
    in_force_date: '2005-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thuong-mai/Luat-Dien-luc-2004-28-2004-QH11-1815.aspx',
    description: 'Electricity regulation: generation, transmission, distribution, pricing, renewable energy.',
    classification: 'ingestable',
  },
  {
    id: 'geology-minerals-law-2024',
    title: 'Luật Địa chất và khoáng sản 2024',
    title_en: 'Law on Geology and Minerals 2024',
    short_name: 'Luật ĐCKS 2024',
    official_number: '54/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-11-29',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Tai-nguyen-Moi-truong/Luat-Dia-chat-va-khoang-san-2024-54-2024-QH15-637048.aspx',
    description: 'Geology and minerals: mineral rights, exploration licensing, mining safety, environmental restoration.',
    classification: 'ingestable',
  },

  // ===== KEY DECREE (exception) =====
  {
    id: 'personal-data-protection-decree-2023',
    title: 'Nghị định 13/2023/NĐ-CP về bảo vệ dữ liệu cá nhân',
    title_en: 'Personal Data Protection Decree 2023',
    short_name: 'NĐ 13/2023',
    official_number: '13/2023/NĐ-CP',
    type: 'decree',
    status: 'in_force',
    issued_date: '2023-04-17',
    in_force_date: '2023-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Cong-nghe-thong-tin/Nghi-dinh-13-2023-ND-CP-bao-ve-du-lieu-ca-nhan-559733.aspx',
    description: 'Vietnam\'s primary PDP regulation until 2025 law takes effect. GDPR-influenced: data subject rights, consent, cross-border transfer, breach notification.',
    classification: 'ingestable',
  },

  // ===== LAWS — ADDITIONAL KEY LEGISLATION =====
  {
    id: 'advertising-law-2012',
    title: 'Luật Quảng cáo 2012',
    title_en: 'Law on Advertising 2012',
    short_name: 'Luật QC 2012',
    official_number: '16/2012/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2012-06-21',
    in_force_date: '2013-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thuong-mai/Luat-quang-cao-2012-16-2012-QH13-142841.aspx',
    description: 'Advertising regulation: online advertising, content restrictions, advertising of regulated products.',
    classification: 'ingestable',
  },
  {
    id: 'price-law-2023',
    title: 'Luật Giá 2023',
    title_en: 'Law on Prices 2023',
    short_name: 'Luật G 2023',
    official_number: '16/2023/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2023-06-19',
    in_force_date: '2024-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thuong-mai/Luat-Gia-2023-16-2023-QH15-567165.aspx',
    description: 'Price regulation: price controls, appraisal, anti-profiteering, essential goods pricing.',
    classification: 'ingestable',
  },
  {
    id: 'standards-technical-regulations-law-2006',
    title: 'Luật Tiêu chuẩn và quy chuẩn kỹ thuật 2006',
    title_en: 'Law on Standards and Technical Regulations 2006',
    short_name: 'Luật TCQCKT 2006',
    official_number: '68/2006/QH11',
    type: 'law',
    status: 'in_force',
    issued_date: '2006-06-29',
    in_force_date: '2007-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thuong-mai/Luat-Tieu-chuan-va-Quy-chuan-ky-thuat-2006-68-2006-QH11-13048.aspx',
    description: 'Standards and technical regulations: conformity assessment, standardization, certification bodies.',
    classification: 'ingestable',
  },
  {
    id: 'product-quality-law-2007',
    title: 'Luật Chất lượng sản phẩm, hàng hóa 2007',
    title_en: 'Law on Product and Goods Quality 2007',
    short_name: 'Luật CLSPHH 2007',
    official_number: '05/2007/QH12',
    type: 'law',
    status: 'in_force',
    issued_date: '2007-11-21',
    in_force_date: '2008-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Thuong-mai/Luat-Chat-luong-san-pham-hang-hoa-2007-05-2007-QH12-57831.aspx',
    description: 'Product quality: producer liability, recall, quality inspection, consumer safety.',
    classification: 'ingestable',
  },
  {
    id: 'measurement-law-2011',
    title: 'Luật Đo lường 2011',
    title_en: 'Law on Measurement 2011',
    short_name: 'Luật ĐL 2011',
    official_number: '04/2011/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2011-11-11',
    in_force_date: '2012-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Linh-vuc-khac/Luat-do-luong-2011-04-2011-QH13-131761.aspx',
    description: 'Measurement and metrology: legal measurement units, calibration, verification.',
    classification: 'ingestable',
  },
  {
    id: 'nuclear-energy-law-2008',
    title: 'Luật Năng lượng nguyên tử 2008',
    title_en: 'Law on Atomic Energy 2008',
    short_name: 'Luật NLNT 2008',
    official_number: '18/2008/QH12',
    type: 'law',
    status: 'in_force',
    issued_date: '2008-06-03',
    in_force_date: '2009-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Tai-nguyen-Moi-truong/Luat-nang-luong-nguyen-tu-2008-18-2008-QH12-67557.aspx',
    description: 'Nuclear energy: radiation safety, nuclear facilities, radioactive waste, nuclear security.',
    classification: 'ingestable',
  },
  {
    id: 'science-technology-law-2013',
    title: 'Luật Khoa học và công nghệ 2013',
    title_en: 'Law on Science and Technology 2013',
    short_name: 'Luật KHCN 2013',
    official_number: '29/2013/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2013-06-18',
    in_force_date: '2014-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Cong-nghe-thong-tin/Luat-khoa-hoc-va-cong-nghe-2013-29-2013-QH13-197387.aspx',
    description: 'Science and technology: R&D funding, technology transfer, research organizations.',
    classification: 'ingestable',
  },
  {
    id: 'technology-transfer-law-2017',
    title: 'Luật Chuyển giao công nghệ 2017',
    title_en: 'Law on Technology Transfer 2017',
    short_name: 'Luật CGCN 2017',
    official_number: '07/2017/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2017-06-19',
    in_force_date: '2018-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/So-huu-tri-tue/Luat-chuyen-giao-cong-nghe-2017-07-2017-QH14-318690.aspx',
    description: 'Technology transfer: licensing, technology valuation, state management, restricted technologies.',
    classification: 'ingestable',
  },
  {
    id: 'cyber-information-security-law-2018-amendment',
    title: 'Luật sửa đổi Bộ luật Hình sự 2017',
    title_en: 'Law Amending the Penal Code 2017',
    short_name: 'Luật SĐ BLHS 2017',
    official_number: '12/2017/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2017-06-20',
    in_force_date: '2018-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Trach-nhiem-hinh-su/Luat-sua-doi-Bo-luat-Hinh-su-2017-12-2017-QH14-318694.aspx',
    description: 'Penal Code amendment: corrects and supplements cybercrime and economic crime provisions (Art. 285-294).',
    classification: 'ingestable',
  },
  {
    id: 'child-law-2016',
    title: 'Luật Trẻ em 2016',
    title_en: 'Law on Children 2016',
    short_name: 'Luật TE 2016',
    official_number: '102/2016/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2016-04-05',
    in_force_date: '2017-06-01',
    url: 'https://thuvienphapluat.vn/van-ban/Giao-duc/Luat-tre-em-2016-102-2016-QH13-303829.aspx',
    description: 'Children\'s rights: online safety, child data protection, child exploitation prevention.',
    classification: 'ingestable',
  },
  {
    id: 'gender-equality-law-2006',
    title: 'Luật Bình đẳng giới 2006',
    title_en: 'Law on Gender Equality 2006',
    short_name: 'Luật BĐG 2006',
    official_number: '73/2006/QH11',
    type: 'law',
    status: 'in_force',
    issued_date: '2006-11-29',
    in_force_date: '2007-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Quyen-dan-su/Luat-Binh-dang-gioi-2006-73-2006-QH11-16tried.aspx',
    description: 'Gender equality: non-discrimination, equal opportunities, workplace equality.',
    classification: 'ingestable',
  },
  {
    id: 'domestic-violence-prevention-law-2022',
    title: 'Luật Phòng, chống bạo lực gia đình 2022',
    title_en: 'Law on Prevention of Domestic Violence 2022',
    short_name: 'Luật PCBLGĐ 2022',
    official_number: '13/2022/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2022-11-14',
    in_force_date: '2023-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Van-hoa-Xa-hoi/Luat-Phong-chong-bao-luc-gia-dinh-2022-13-2022-QH15-535870.aspx',
    description: 'Domestic violence: protection orders, shelters, mediation, offender programs.',
    classification: 'ingestable',
  },
  {
    id: 'cinematography-law-2022',
    title: 'Luật Điện ảnh 2022',
    title_en: 'Law on Cinematography 2022',
    short_name: 'Luật ĐA 2022',
    official_number: '05/2022/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2022-06-15',
    in_force_date: '2023-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Van-hoa-Xa-hoi/Luat-Dien-anh-2022-05-2022-QH15-519921.aspx',
    description: 'Film regulation: classification, censorship, online streaming, foreign film distribution.',
    classification: 'ingestable',
  },
  {
    id: 'cultural-heritage-law-2024',
    title: 'Luật Di sản văn hóa 2024',
    title_en: 'Law on Cultural Heritage 2024',
    short_name: 'Luật DSVH 2024',
    official_number: '62/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-12-06',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Van-hoa-Xa-hoi/Luat-Di-san-van-hoa-2024-62-2024-QH15-637090.aspx',
    description: 'Cultural heritage: tangible/intangible heritage, museum regulation, archaeological sites.',
    classification: 'ingestable',
  },
  {
    id: 'publishing-law-2012',
    title: 'Luật Xuất bản 2012',
    title_en: 'Law on Publishing 2012',
    short_name: 'Luật XB 2012',
    official_number: '19/2012/QH13',
    type: 'law',
    status: 'in_force',
    issued_date: '2012-11-20',
    in_force_date: '2013-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Van-hoa-Xa-hoi/Luat-xuat-ban-2012-19-2012-QH13-155760.aspx',
    description: 'Publishing: book publishing, e-publishing, content review, foreign publication import.',
    classification: 'ingestable',
  },
  {
    id: 'urban-rural-planning-law-2024',
    title: 'Luật Quy hoạch đô thị và nông thôn 2024',
    title_en: 'Law on Urban and Rural Planning 2024',
    short_name: 'Luật QHĐTNT 2024',
    official_number: '47/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-11-25',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Xay-dung-Do-thi/Luat-Quy-hoach-do-thi-va-nong-thon-2024-47-2024-QH15-637018.aspx',
    description: 'Urban and rural planning: master plans, zoning, building density, green spaces, smart city.',
    classification: 'ingestable',
  },
  {
    id: 'public-asset-management-law-2017',
    title: 'Luật Quản lý, sử dụng tài sản công 2017',
    title_en: 'Law on Management and Use of Public Assets 2017',
    short_name: 'Luật QLSDTSC 2017',
    official_number: '15/2017/QH14',
    type: 'law',
    status: 'in_force',
    issued_date: '2017-06-21',
    in_force_date: '2018-01-01',
    url: 'https://thuvienphapluat.vn/van-ban/Tai-chinh-nha-nuoc/Luat-Quan-ly-su-dung-tai-san-cong-2017-15-2017-QH14-322908.aspx',
    description: 'Public asset management: state property, asset disposal, leasing, PPP projects.',
    classification: 'ingestable',
  },
  {
    id: 'cooperatives-law-2023',
    title: 'Luật Hợp tác xã 2023',
    title_en: 'Law on Cooperatives 2023',
    short_name: 'Luật HTX 2023',
    official_number: '17/2023/QH15',
    type: 'law',
    status: 'in_force',
    issued_date: '2023-06-20',
    in_force_date: '2024-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Doanh-nghiep/Luat-Hop-tac-xa-2023-17-2023-QH15-567167.aspx',
    description: 'Cooperatives: formation, governance, member rights, agricultural cooperatives, dissolution.',
    classification: 'ingestable',
  },
  {
    id: 'prevention-human-trafficking-law-2024',
    title: 'Luật Phòng, chống mua bán người 2024',
    title_en: 'Law on Prevention and Combat of Human Trafficking 2024',
    short_name: 'Luật PCMBN 2024',
    official_number: '56/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-11-29',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Trach-nhiem-hinh-su/Luat-Phong-chong-mua-ban-nguoi-2024-56-2024-QH15-637051.aspx',
    description: 'Anti-trafficking: victim protection, cross-border cooperation, online exploitation.',
    classification: 'ingestable',
  },
  {
    id: 'peoples-air-defense-law-2024',
    title: 'Luật Phòng không nhân dân 2024',
    title_en: 'Law on People\'s Air Defense 2024',
    short_name: 'Luật PKND 2024',
    official_number: '53/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-11-28',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Luat-Phong-khong-nhan-dan-2024-53-2024-QH15-637047.aspx',
    description: 'People\'s air defense: civil defense, air raid shelters, drone regulation.',
    classification: 'ingestable',
  },
  {
    id: 'defense-industry-law-2024',
    title: 'Luật Công nghiệp quốc phòng, an ninh và động viên công nghiệp 2024',
    title_en: 'Law on Defense Industry, Security and Industrial Mobilization 2024',
    short_name: 'Luật CNQP 2024',
    official_number: '38/2024/QH15',
    type: 'law',
    status: 'not_yet_in_force',
    issued_date: '2024-06-27',
    in_force_date: '2025-07-01',
    url: 'https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Luat-Cong-nghiep-quoc-phong-2024-38-2024-QH15-617643.aspx',
    description: 'Defense industry: military manufacturing, dual-use technology, industrial mobilization.',
    classification: 'ingestable',
  },
];

function main(): void {
  console.log('Vietnamese Law MCP — Census');
  console.log('===========================\n');
  console.log('  Source:  vbpl.vn / thuvienphapluat.vn (cross-referenced)');
  console.log('  Method:  Curated master list + thuvienphapluat.vn URLs');
  console.log('  License: Government Open Data / Open Access\n');

  // Compute stats
  const byType: Record<string, number> = {};
  const byStatus: Record<string, number> = {};
  for (const law of VIETNAMESE_LAWS) {
    byType[law.type] = (byType[law.type] ?? 0) + 1;
    byStatus[law.status] = (byStatus[law.status] ?? 0) + 1;
  }

  // Check for duplicate IDs
  const ids = new Set<string>();
  for (const law of VIETNAMESE_LAWS) {
    if (ids.has(law.id)) {
      console.error(`  ERROR: Duplicate ID: ${law.id}`);
    }
    ids.add(law.id);
  }

  // Sort by type then date
  const sorted = [...VIETNAMESE_LAWS].sort((a, b) => {
    const typeOrder = { constitution: 0, code: 1, law: 2, ordinance: 3, decree: 4 };
    const ta = typeOrder[a.type] ?? 5;
    const tb = typeOrder[b.type] ?? 5;
    if (ta !== tb) return ta - tb;
    return a.issued_date.localeCompare(b.issued_date);
  });

  const census: CensusOutput = {
    generated_at: new Date().toISOString(),
    source: 'vbpl.vn / thuvienphapluat.vn (curated master list)',
    description: 'Census of Vietnamese national legislation: Constitution, Codes, Laws, key Ordinances, and PDP Decree',
    stats: {
      total: sorted.length,
      by_type: byType,
      by_status: byStatus,
      class_ingestable: sorted.filter(a => a.classification === 'ingestable').length,
      class_inaccessible: sorted.filter(a => a.classification === 'inaccessible').length,
      class_metadata_only: sorted.filter(a => a.classification === 'metadata_only').length,
    },
    laws: sorted,
  };

  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(CENSUS_PATH, JSON.stringify(census, null, 2) + '\n');

  console.log(`${'='.repeat(50)}`);
  console.log('CENSUS COMPLETE');
  console.log('='.repeat(50));
  console.log(`  Total laws discovered: ${sorted.length}`);
  console.log(`  By type:`);
  for (const [type, count] of Object.entries(byType).sort()) {
    console.log(`    ${type.padEnd(15)} ${count}`);
  }
  console.log(`  By status:`);
  for (const [status, count] of Object.entries(byStatus).sort()) {
    console.log(`    ${status.padEnd(20)} ${count}`);
  }
  console.log(`  Ingestable:  ${census.stats.class_ingestable}`);
  console.log(`\n  Output: ${CENSUS_PATH}`);
}

main();
